### ISSUE TITLE
Results are different between different runs

### ISSUE THREAD

**Issue by chenyj8** [apcamargo/genomad#133]
I have a dataset with ~30000 contigs, and I performed two runs of genomad (end-to-end, note that I didn't include "--enable-score-calibration" flag):

Run1: All contigs were used as input 

Run2: A subset of ~10000 contigs were used as input

The commands of these two runs are the same: genomad end-to-end --cleanup genomad_input genomad_output genomad_db

I found that these two runs give different results. For example, a contig is identified as a full virus in run 1, but it is a provirus in run2.

**Comment by apcamargo** [comment]
This is likely due to the fact that the MMseqs2 annotation can change depending on the order of the sequences in a FASTA file. For more details, see this issue: https://github.com/apcamargo/genomad/issues/33

The only way to completely remove this source of variability is to clone geNomad's source code, [remove these two lines](https://github.com/apcamargo/genomad/blob/52dc1b20e60be9a87573105d14ac38f711fc06aa/genomad/mmseqs2.py#L120-L121), and install from your custom code. Keep in mind that this will make geNomad run much more slowly.

**Comment by chenyj8** [comment]
> This is likely due to the fact that the MMseqs2 annotation can change depending on the order of the sequences in a FASTA file. For more details, see this issue: #33
> 
> The only way to completely remove this source of variability is to clone geNomad's source code, [remove these two lines](https://github.com/apcamargo/genomad/blob/52dc1b20e60be9a87573105d14ac38f711fc06aa/genomad/mmseqs2.py#L120-L121), and install from your custom code. Keep in mind that this will make geNomad run much more slowly.

Thanks for the clarification. Would it be possible to annotate each sequence individually to remove the variability across different runs. Looks like this is how DRAM (https://github.com/WrightonLabCSU/DRAM) works.

**Comment by chenyj8** [comment]
> I think they just don't use the heuristic that geNomad uses to speed things up. In a prior release I did a couple of modifications to alleviate this issue, but the only way to eliminate it entirely is to remove those lines I mentioned in my last comment.

Thanks again!

**Comment by apcamargo** [comment]
No worries. I'm sorry that I can't offer a better solution.

In the future, I could add a flag to disable these heuristics. However, I'd have to do some benchmarking before providing this option.
