### ISSUE TITLE
Provirus detection changes when more input is given

### ISSUE THREAD

**Issue by nikolasbasler** [apcamargo/genomad#31]
I have a large number of metagenomic assemblies (virus-enriched in the wet lab). When I concatenate the assemblies into one file and run geNomad end-to-end (with score calibration), I see a few proviruses that are not detected when I run geNomad on the individual assemblies, with the same settings. The proviruses appear in the find-proviruses folder as well as in the summary.

This might be an expected behaviour but it's not really clear to me. An explanation would be highly appreciated. Also, if this is expected, would the prophage prediction of the concatenated input be more accurate than that of the individual assemblies?

In case it helps to clarify what I mean, this is the summary from the concatenated input:
```
$ grep "NODE_A77_length_14406_cov_85.369321_CH_17692_sum_ile_d" ALL.SAMPLES_1kb.contigs_virus_summary.tsv 
NODE_A77_length_14406_cov_85.369321_CH_17692_sum_ile_d|provirus_6327_14404	8078	Provirus	6327-14404	14	11	0.9952	0.0014	1	11.4948	Viruses;Duplodnaviria;Heunggongvirae;Uroviricota;Caudoviricetes
```
And this is from the individual assembly:
```
$ grep "NODE_A77_length_14406_cov_85.369321_CH_17692_sum_ile_d" CH_17692_sum_ile_d_1kb.contigs_virus_summary.tsv 
NODE_A77_length_14406_cov_85.369321_CH_17692_sum_ile_d	14406	No terminal repeats	NA	20	11	0.9429	0.0109	1	9.7680	Viruses;Duplodnaviria;Heunggongvirae;Uroviricota;Caudoviricetes
```

Cheers!

**Comment by apcamargo** [comment]
Hi @nikolasbasler 

It is expected that scores will change when you use score calibration, since the composition of the entire sample you are classifying will affect the score of individual sequences. This is a desired behaviour and you can read more about it [here](https://portal.nersc.gov/genomad/score_calibration.html).

Regarding proviruses. If geNomad finds a potential provirus in a sequence there are two possibilities: (1) if the virus score of the provirus is higher than the virus score of the full sequence, it will output the provirus; (2) if the virus score of the entire sequence is higher than the virus score of the provirus, geNomad will ignore the provirus and output the full sequence as a viral genome.

What is interesting in your case is that the calibration inverted the order. When you executed it on the individual assembly, the full sequence had a higher score, but when you ran on a concatenated input the provirus had a higher calibrated score.

Calibration works well when the assemblies have more than 1,000 sequences. Is that the case for you? Answering to your question: I'd trust the classification of the concatenated assemblies more, since the calibration works better when you have more sequences. If you want to be extra safe, you might want to take a look at the full sequence to be sure that the provirus demarcation looks good.

**Comment by nikolasbasler** [comment]
Hi @apcamargo 
Thanks for your detailed answer! The concatenated file had several hundred thousand sequences and only 2 proviruses were detected there that didn't show up in the individual datasets. So it's a very rare event. The individual files where it did happen had around 9000 sequences each.

I will use the concatenated input.
Cheers!

**Comment by apcamargo** [comment]
You're welcome :)
