### ISSUE TITLE
Could update to ICTV's VMR 21(MSL #37)?

### ISSUE THREAD

**Issue by mijiandui** [apcamargo/genomad#4]
Dear @apcamargo!

    Thanks a lot for your excellent work.
    I noticed the software used the ICTV's VMR number 19, however, the ICTV has updated the new taxonomy. Could you update the database based on the new taxonomy? or shared the procedures to make the database.

    Thanks a lot.
     Warm Regards
     Jiandui Mi

**Comment by apcamargo** [comment]
Hey @mijiandui 

I plan to keep the database updated to the newest taxonomy. I just saw that there's a VMR 20, but it seems that the taxa didn't change (maybe some new genomes were added for existing species? I'll look into that).

When ICTV "releases" new taxa, it might take a few weeks/months for me to update geNomad's database because I depend on NCBI updating the taxonomy of the sequences there.

Thanks for keeping me informed!

**Comment by mijiandui** [comment]
Yes, it released in 2022, but named [VMR_20-190822_MSL37.3.xlsx]. Thanks a lot for your hard work. NCBI database have updated to 214 on September, 2022 (https://ftp.ncbi.nlm.nih.gov/refseq/release/). 
  
     Thanks again.
      Warm Regards
      Jiandui Mi

**Comment by apcamargo** [comment]
I just checked and the taxa remain the same. You can use the current database :)

An update to the taxa will come out next year and I'll update geNomad's database as soon as possible.

**Comment by mijiandui** [comment]
Dear apcamargo，

        Thanks  a lot!
