### ISSUE TITLE
Inquiry on threshold

### ISSUE THREAD

**Issue by songmj86** [apcamargo/genomad#61]
Hi 

I would like to ask the proper threshold to define the plasmid, virus, and chromosme?

Thank you !

**Comment by apcamargo** [comment]
Hi @songmj86,

There's no straightforward answer to your question, unfortunately. It really depends on your goal (i.e. how conservative do you want/need to be).

If you use the [score calibration feature](https://portal.nersc.gov/genomad/score_calibration.html), scores will be very close to probabilities, so you can set interpretable cutoffs (e.g., at least 90% probability of being a plasmid or virus).

Otherwise, the default cutoffs work pretty well. [geNomad already applies some filters](https://portal.nersc.gov/genomad/post_classification_filtering.html) to try to avoid some obvious mispredictions. If you are interested in viruses, can also couple geNomad with CheckV to retain only medium/high-quality genomes.

**Comment by songmj86** [comment]
Thank you for your kindness!
