### ISSUE TITLE
Purpose of the `BranchAttention` class in `igloo.py`

### ISSUE THREAD

**Issue by a-piece-of-teemo** [apcamargo/genomad#70]
Hello author, in your igloo.py, I noticed this piece of code, and I am curious if you have used it? Because I saw another similar function, Branch_Attention, in the aggregated_classification module, and I am curious about the relationship between these two functions.

![image](https://github.com/apcamargo/genomad/assets/113283540/e3efb87c-d7e5-4aff-ab05-d0970b58c5eb)

**Comment by apcamargo** [comment]
This is the Keras layer that I used to train the score aggregation model. Because the network is pretty small, I extracted the weights and implemented it in Numpy. You can find the weights and the Numpy implementation [here](https://github.com/apcamargo/genomad/blob/2bdbdd53d7171145338e7e3b53eefca0204f7120/genomad/modules/aggregated_classification.py#L8-L27).
